author: "Jose Haro <joseharoperalta at gmail.com>"
category: "http"
summary: "Monitoring Hook for Ejabberd"
home: "https://github.com/abunuwas/mod_hello_world/tree/master/"
url: "git@github.com:jadahl/mod_restful.git"